steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'us-central1-docker.pkg.dev/t-isotope-421803demo-docker-image/first_repo:tag1'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'us-central1-docker.pkg.dev/t-isotope-421803/demo-docker-image/first_repo:tag1'


      



