steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/demo-docker-image/first_repo2:$COMMIT_SHA"
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - "push"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/demo-docker-image/first_repo2:$COMMIT_SHA"






