name: Python application test with Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint

    #- name: Test with pytest
    #  run: |
    #    make test
    #- name: Format code
    #  run: |
    #    make format
  deploy:
    runs-on: ubuntu-latest #run this workflow on ubuntu instance
    permissions: #make sure we add permission to read and write package
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/891346628012/locations/global/workloadIdentityPools/actions/providers/github'
        service_account: 'user1-383@t-isotope-421803.iam.gserviceaccount.com'
        
    #- name: Build and push Docker image
    #  uses: docker/build-push-action@v4
    #  with:
    #    push: true
    #    tags: flask_actions_cloud_build_gke_app:latest
    


